language: python
sudo: False
python:
  - "2.7"
install:
  - pip install .
  - pip install flake8
  - pip install coveralls
script:
  - flake8 smoketest
  - cd testapp && python manage.py test
  - cd testapp && coverage run --source=../smoketest manage.py test
after_success:
  - coveralls
