language: python
sudo: False
python:
  - "2.7"
  - "3.5"
env:
  - DJANGO="Django>=1.8.0,<1.9.0"
  - DJANGO="Django>=1.9.0,<1.10.0"
  - DJANGO="Django>=1.10,<1.11.0"
install:
  - pip install .
  - pip install flake8
  - pip install coveralls
script:
  - flake8 smoketest
  - python runtests.py
  - coverage run --source=smoketest runtests.py
after_success:
  - coveralls
